"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function IntakeForm() {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(formData: FormData) { setBusy(true); setError(""); try { const response = await fetch("/api/generate-report", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(formData.entries())) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not create your reading"); router.push(`/report/${result.report_id}`); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong"); setBusy(false); } }
  const cls = "mt-2 w-full rounded-sm border border-[#c9bcad] bg-[#fffdf8] px-4 py-3 outline-none focus:border-[#9b3c2b]";
  return <form action={submit} className="rounded-sm border border-[#d7cbbd] bg-[#fffaf0] p-6 shadow-[0_20px_50px_rgba(71,49,32,.09)] sm:p-9"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#9b3c2b]">Create a reading</p><h2 className="mb-7 mt-2 text-3xl">Birth details</h2><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm sm:col-span-2">Subject name<input required name="subject_name" maxLength={80} className={cls} placeholder="e.g. Aisha" /></label><label className="text-sm sm:col-span-2">Email<input required type="email" name="email" className={cls} placeholder="you@example.com" /></label><label className="text-sm">Birth date<input required type="date" name="birth_date" max={new Date().toISOString().slice(0,10)} className={cls} /></label><label className="text-sm">Birth time <span className="text-[#877b70]">(optional)</span><input type="time" name="birth_time" className={cls} /></label><label className="text-sm">Gender<select required name="gender" defaultValue="" className={cls}><option value="" disabled>Select</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></select></label><label className="text-sm">Focus<select required name="question_type" defaultValue="child_potential" className={cls}><option value="child_potential">Child potential</option><option value="career">Career</option><option value="wealth">Wealth</option><option value="relationship">Relationship</option></select></label></div>{error && <p role="alert" className="mt-5 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button disabled={busy} className="mt-7 w-full bg-[#9b3c2b] px-5 py-4 font-semibold text-white disabled:opacity-60">{busy ? "Preparing your reading…" : "Reveal the four pillars"}</button></form>;
}
