import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import UpgradeButton from "@/app/components/upgrade-button";
import type { BaziReport } from "@/lib/types";

export const dynamic = "force-dynamic";
export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const db = await createClient(); const { data, error } = await db.from("bazi_reports").select("*").eq("id", id).maybeSingle(); if (error || !data) notFound(); const report = data as BaziReport;
  await db.from("audit_logs").insert({ actor: "visitor", action: "report.viewed", target_table: "bazi_reports", target_id: id, payload: {} });
  const pillars = [["Year",report.year_pillar],["Month",report.month_pillar],["Day",report.day_pillar],["Hour",report.hour_pillar ?? "Birth time unknown"]]; const insights = report.insights?.split("\n").filter(Boolean) ?? [];
  return <main className="min-h-screen"><header className="mx-auto flex max-w-5xl items-center justify-between px-6 py-6"><Link href="/" className="font-semibold tracking-wide">REALM OF QIMEN</Link><span className="text-xs uppercase tracking-widest text-[#877b70]">Personal reading</span></header><article className="mx-auto max-w-5xl px-6 pb-20 pt-8"><div className="border-b border-[#cfc2b4] pb-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#9b3c2b]">Four pillars · {report.question_type.replace("_"," ")}</p><h1 className="mt-3 text-5xl">{report.subject_name}</h1><p className="mt-4 text-[#74685e]">Born {new Date(`${report.birth_date}T12:00:00`).toLocaleDateString("en", { dateStyle: "long" })}</p></div><div className="grid gap-px overflow-hidden border border-[#cfc2b4] bg-[#cfc2b4] sm:grid-cols-4">{pillars.map(([label,value])=><div key={label} className="bg-[#fffaf0] p-6"><p className="text-xs uppercase tracking-widest text-[#9b3c2b]">{label}</p><p className="mt-6 text-xl leading-8">{value ?? "Analysis pending"}</p></div>)}</div>{report.insights ? <div className="mt-12 grid gap-10 md:grid-cols-[.75fr_1.25fr]"><section><p className="text-xs uppercase tracking-[.2em] text-[#9b3c2b]">Element profile</p><h2 className="mt-3 text-3xl leading-tight">{report.element_profile}</h2><p className="mt-5 text-xs text-[#877b70]">Source: {report.insights_source} · confidence {Math.round((report.insights_confidence ?? 0)*100)}%</p></section><section><h2 className="text-3xl">Three reflections</h2><ol className="mt-5 space-y-4">{insights.map((insight,i)=><li key={i} className="border-l border-[#b7422d] py-2 pl-5 leading-7">{insight.replace(/^\d+\.\s*/,"")}</li>)}</ol></section></div> : <div className="my-12 border border-amber-300 bg-amber-50 p-6"><h2 className="text-xl">Analysis pending</h2><p className="mt-2 text-sm">We saved this reading and will update it shortly.</p></div>}<section className="mt-14 bg-[#211b16] p-8 text-[#f6f0e4] sm:flex sm:items-center sm:justify-between sm:gap-8"><div><p className="text-xs uppercase tracking-widest text-[#d99a85]">Go deeper</p><h2 className="mt-2 text-3xl">Turn reflection into a plan.</h2><p className="mt-2 text-sm text-[#cfc5bd]">Book a private consult for fuller context and practical next steps.</p></div><UpgradeButton reportId={report.id} /></section></article></main>;
}
