import Link from "next/link";

export const metadata = { title: "Privacy Notice | Realm of Qimen" };

export default function PrivacyPage() {
  return <LegalPage title="Privacy Notice" updated="1 August 2026">
    <p>Realm of Qimen respects your privacy. This notice applies to our Bazi, Qimen, Feng Shui, report, consultation, and related services. It explains what information we collect, why we use it, and the choices available to you.</p>
    <Section title="Information we may collect"><p>The information needed depends on the service requested. It may include:</p><ul><li>Your name, email address, mobile number, and communication preferences.</li><li>The name, gender, date and time of birth, and place of birth of the person receiving a Bazi or Qimen reading.</li><li>Questions, concerns, feedback, and information voluntarily provided for a reading or consultation.</li><li>For Feng Shui services, property details such as an address or general location, floor plan, orientation, photographs, room use, and relevant occupant information.</li><li>Technical and service records needed for security, troubleshooting, delivery, and improvement.</li></ul><p>Please provide only information that is relevant to the service.</p></Section>
    <Section title="How we use the information"><ul><li>Calculate charts and prepare the requested reading, report, or consultation.</li><li>Display, store, and—when requested—email or otherwise deliver the service.</li><li>Respond when you ask questions or express interest in another service.</li><li>Review feedback, improve quality, and investigate errors.</li><li>Protect the service, maintain necessary records, and meet legal obligations.</li></ul><p>Updates and promotional messages are optional. We will use contact details for those messages only when separate consent has been given.</p></Section>
    <Section title="Information about another person or a child"><p>If you provide information about another person, you confirm that you have authority or permission to do so. Information about a child must be submitted by the child&apos;s parent, legal guardian, or another adult authorised to provide it. We limit collection to information needed for the requested service and do not make personal readings or identifying details public.</p></Section>
    <Section title="Service providers and overseas processing"><p>We use service providers for website hosting, database storage, report generation, communications, and email delivery. These providers may process information outside Singapore. We take reasonable steps to use reputable providers and appropriate safeguards. We do not sell personal information.</p></Section>
    <Section title="Retention and security"><p>We retain information only while it is reasonably needed to provide the service, support requested follow-up, improve quality, resolve disputes, or meet legal and business requirements. Different information may have different retention periods. We use reasonable technical and organisational safeguards, but no internet service can guarantee absolute security.</p></Section>
    <Section title="Your choices and requests"><p>You may ask to access or correct information, withdraw consent, or request deletion. Withdrawal or deletion may mean that we can no longer provide or retrieve a reading. Some information may be retained where required for legal, security, dispute-resolution, or legitimate record-keeping purposes.</p><p><Link className="font-semibold underline underline-offset-4" href="/data-request">Request access, correction, withdrawal, or deletion</Link></p></Section>
    <Section title="Contact"><p>For privacy questions or complaints, email <a className="underline underline-offset-4" href="mailto:realmofqimen@gmail.com">realmofqimen@gmail.com</a>.</p></Section>
    <p className="text-sm text-[#665a50]">This notice may be updated as the services develop. The latest version will appear on this page.</p>
  </LegalPage>;
}

function LegalPage({title,updated,children}:{title:string;updated:string;children:React.ReactNode}){return <main className="mx-auto max-w-3xl px-6 py-12 sm:py-16"><Link href="/" className="text-sm font-semibold tracking-wide">REALM OF QIMEN</Link><p className="mt-12 text-xs font-bold uppercase tracking-[.22em] text-[#9b3c2b]">Legal</p><h1 className="mt-2 text-5xl">{title}</h1><p className="mt-3 text-sm text-[#74685e]">Last updated: {updated}</p><div className="mt-10 space-y-9 leading-8 text-[#3c3028]">{children}</div></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="text-2xl">{title}</h2><div className="mt-3 space-y-3 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6">{children}</div></section>}
