import Link from "next/link";

export const metadata = { title: "Terms & Disclaimer | Realm of Qimen" };

export default function TermsPage(){return <main className="mx-auto max-w-3xl px-6 py-12 sm:py-16"><Link href="/" className="text-sm font-semibold tracking-wide">REALM OF QIMEN</Link><p className="mt-12 text-xs font-bold uppercase tracking-[.22em] text-[#9b3c2b]">Legal</p><h1 className="mt-2 text-5xl">Terms &amp; Disclaimer</h1><p className="mt-3 text-sm text-[#74685e]">Last updated: 1 August 2026</p><div className="mt-10 space-y-9 leading-8 text-[#3c3028]">
  <Section title="Using this service"><p>By requesting a report, you agree to these terms and our <Link className="underline underline-offset-4" href="/privacy">Privacy Notice</Link>. You must provide accurate information and use the service lawfully.</p></Section>
  <Section title="Authority to submit a child’s details"><p>You confirm that you are the child&apos;s parent or legal guardian, or that you otherwise have authority to provide the child&apos;s information and request the reading.</p></Section>
  <Section title="Reflective guidance, not professional advice"><p>Bazi is a traditional interpretive system. Reports are offered for personal reflection and parenting insight. They do not determine a child&apos;s future or provide a complete description of the child.</p><p>The service is not a substitute for medical, psychological, educational, legal, financial, religious, or other professional advice. Seek a qualified professional where appropriate, especially for concerns involving health, safety, development, learning, or emotional wellbeing.</p></Section>
  <Section title="Accuracy and automated generation"><p>Results depend on the birth details supplied. Reports may be prepared with automated calculation and language-generation tools. We work to improve accuracy and consistency, but interpretations may contain errors, omissions, or statements that do not fit every situation. Please use your own judgement and do not make important decisions based only on a report.</p></Section>
  <Section title="Availability and changes"><p>We may update, suspend, or withdraw parts of the service, including free features, while the website develops. We do not guarantee uninterrupted availability or permanent access to a report, so you should keep a copy if it is important to you.</p></Section>
  <Section title="Intellectual property"><p>The website design, report format, original wording and supporting materials belong to Realm of Qimen or its licensors. A report may be saved and shared for the family&apos;s personal, non-commercial use. It may not be resold, republished as a competing service, or used to train another product without permission.</p></Section>
  <Section title="Responsibility"><p>To the extent permitted by law, Realm of Qimen is not responsible for indirect or consequential loss arising from reliance on a report or inability to use the service. Nothing in these terms excludes rights or responsibilities that cannot lawfully be excluded.</p></Section>
  <Section title="Contact"><p>Questions about these terms may be sent to <a className="underline underline-offset-4" href="mailto:realmofqimen@gmail.com">realmofqimen@gmail.com</a>.</p></Section>
 </div></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="text-2xl">{title}</h2><div className="mt-3 space-y-3">{children}</div></section>}
