import Link from "next/link";

export const metadata = { title: "Terms & Disclaimer | Realm of Qimen" };

export default function TermsPage(){return <main className="mx-auto max-w-3xl px-6 py-12 sm:py-16"><Link href="/" className="text-sm font-semibold tracking-wide">REALM OF QIMEN</Link><p className="mt-12 text-xs font-bold uppercase tracking-[.22em] text-[#007789]">Legal</p><h1 className="mt-2 text-5xl">Terms &amp; Disclaimer</h1><p className="mt-3 text-sm text-[#5d6f75]">Last updated: 1 August 2026</p><div className="mt-10 space-y-9 leading-8 text-[#272727]">
  <Section title="Using our services"><p>These terms apply to Realm of Qimen&apos;s Bazi, Qimen, Feng Shui, report, consultation, and related services. By requesting or using a service, you agree to these terms and our <Link className="underline underline-offset-4" href="/privacy">Privacy Notice</Link>. You must provide accurate information and use the services lawfully.</p></Section>
  <Section title="Information about another person"><p>If a reading or consultation concerns another person, you confirm that you have authority or permission to provide that person&apos;s information. For a child, you confirm that you are the parent or legal guardian, or are otherwise authorised to submit the child&apos;s details.</p></Section>
  <Section title="Interpretive guidance, not professional advice"><p>Bazi, Qimen, and Feng Shui are traditional interpretive systems. Readings are offered for personal reflection, planning, and general insight. They do not determine the future, guarantee an outcome, or provide a complete description of a person, relationship, property, or situation.</p><p>Our services are not a substitute for medical, psychological, educational, legal, financial, architectural, engineering, safety, religious, or other professional advice. Seek an appropriately qualified professional where needed. Do not delay urgent or professional help because of a reading.</p></Section>
  <Section title="Accuracy and automated assistance"><p>Results depend on the information supplied and the interpretive method used. Reports may be prepared with automated calculation and language-generation tools. We work to improve accuracy and consistency, but a reading may contain errors, omissions, or statements that do not fit every situation. Use your own judgement and do not make an important decision based only on a reading.</p></Section>
  <Section title="Feng Shui information"><p>Any comments about a property are interpretive and are not a physical inspection, building assessment, safety certification, valuation, or substitute for advice from an architect, engineer, contractor, surveyor, or other qualified professional.</p></Section>
  <Section title="Availability and changes"><p>We may update, suspend, or withdraw parts of the services, including free features, while the website develops. We do not guarantee uninterrupted availability or permanent access to a report, so you should keep a copy if it is important to you.</p></Section>
  <Section title="Intellectual property"><p>The website design, report formats, original wording, and supporting materials belong to Realm of Qimen or its licensors. A report may be saved and shared for the recipient&apos;s personal, non-commercial use. It may not be resold, republished as a competing service, or used to train another product without permission.</p></Section>
  <Section title="Responsibility"><p>To the extent permitted by law, Realm of Qimen is not responsible for indirect or consequential loss arising from reliance on a reading or inability to use a service. Nothing in these terms excludes rights or responsibilities that cannot lawfully be excluded.</p></Section>
  <Section title="Contact"><p>Questions about these terms may be sent to <a className="underline underline-offset-4" href="mailto:realmofqimen@gmail.com">realmofqimen@gmail.com</a>.</p></Section>
 </div></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="text-2xl">{title}</h2><div className="mt-3 space-y-3">{children}</div></section>}
