import type { CommunicationGuidance } from "@/lib/types";

type Profile = { works: [string, string, string]; avoid: [string, string]; phrases: [string, string] };

const profiles: Record<string, Profile> = {
  Jia: { works: ["Be clear about what needs to happen and explain the reason. This helps {name} understand the direction, not only the rule.", "Give {name} time to finish a thought before correcting or redirecting the conversation.", "When a plan changes, explain what has changed and what remains the same."], avoid: ["Avoid relying on hints when a direct explanation would be clearer.", "Try not to change an agreed plan without explaining why."], phrases: ["Here is what needs to happen, and this is why it matters.", "Tell me which part does not feel right to you. I will listen first."] },
  Yi: { works: ["Invite {name} to share a view before hearing what everyone else thinks. This gives a quieter opinion room to form.", "Offer two suitable choices when there is more than one good way forward.", "Discuss sensitive matters privately, where {name} is less likely to feel watched or compared."], avoid: ["Avoid pressing for an immediate answer in front of other people.", "Try not to mistake a flexible response for having no opinion."], phrases: ["What feels right to you before we hear everyone else's ideas?", "Would you prefer this option, or would you like to suggest another way?"] },
  Bing: { works: ["Acknowledge {name}'s excitement before discussing limits or practical details.", "Keep the main point warm and direct. Long explanations can make the message harder to follow.", "Let {name} contribute an idea before making the final decision together."], avoid: ["Avoid responding so coolly that enthusiasm feels dismissed.", "Try not to give a long lecture while feelings are still running high."], phrases: ["I can see why this matters to you. Let us work out what is possible.", "Tell me your idea first. Then we can decide on the next step together."] },
  Ding: { works: ["Choose a calm, private moment for an important conversation.", "Ask one clear question at a time, then leave enough quiet for {name} to answer.", "Mention the specific change you noticed instead of guessing what {name} feels."], avoid: ["Avoid demanding an answer before {name} has had time to think.", "Try not to correct a sensitive matter in front of other people."], phrases: ["You do not have to answer straight away. We can talk when you are ready.", "I noticed you became quiet. Would you like to tell me about it now or later?"] },
  Wu: { works: ["Give clear and predictable information, especially when routines or plans are changing.", "Break a complicated request into one step at a time.", "Allow {name} a moment to consider the message before asking for a decision."], avoid: ["Avoid rushing {name} simply because the answer seems obvious to someone else.", "Try not to introduce several changes at once without explaining them."], phrases: ["The plan has changed because of this. Here is what will stay the same.", "Take a moment to think. Then tell me which part you want to handle first."] },
  Ji: { works: ["Use a real example and agree on one practical next step.", "Ask what {name} needs, especially after helping other people.", "Recognise the thought behind a helpful action, not only whether the result was perfect."], avoid: ["Avoid giving a vague request and expecting {name} to guess what is needed.", "Try not to assume {name} is fine simply because help is being offered."], phrases: ["You have done a lot for everyone. What would help you now?", "Let us look at one part together and decide what can be done next."] },
  Geng: { works: ["Speak directly and respectfully, using the facts of what happened.", "Let {name} explain a point of view before discussing what needs to change.", "Make expectations clear so {name} does not have to interpret vague hints."], avoid: ["Avoid shaming, sarcasm, or turning the conversation into a contest of wills.", "Try not to push for a solution before everyone understands the problem."], phrases: ["Here is what I saw. I want to hear your side before we decide what happens next.", "I know you want to fix this. Let us understand the whole problem first."] },
  Xin: { works: ["Give specific feedback about one thing at a time.", "Discuss mistakes privately and leave room for {name} to think before responding.", "Notice careful effort as well as the finished result."], avoid: ["Avoid broad criticism such as 'you always' or 'you never'.", "Try not to make perfection the condition for praise or approval."], phrases: ["This part is working well. One thing we can improve is this.", "Take your time. Tell me what you think when you are ready."] },
  Ren: { works: ["Listen to the larger idea first, then help {name} choose one place to begin.", "Set a clear outcome while leaving some freedom in how {name} reaches it.", "Use open questions when a first plan has not worked. This makes room for another approach."], avoid: ["Avoid controlling every step when the destination is already clear.", "Try not to dismiss a new idea before understanding what {name} is trying to solve."], phrases: ["Tell me the whole idea first. Then let us choose one place to begin.", "You can choose how to do it. This is what needs to be finished."] },
  Gui: { works: ["Begin gently by describing what you noticed, without deciding what it means for {name}.", "Leave time between the question and the answer. {name} may need a quiet moment to put feelings into words.", "Explain why something matters instead of repeating the instruction more firmly."], avoid: ["Avoid asking the same question repeatedly when {name} is not ready to answer.", "Try not to dismiss a small concern simply because it seems unimportant to someone else."], phrases: ["I noticed you seem quieter. You can tell me now or come back to me later.", "Here is why this matters. Which part would you like me to explain again?"] },
};

export function buildCommunicationGuidance(dayMasterName: string, name: string, strength: "Strong" | "Balanced" | "Weak"): CommunicationGuidance {
  const profile = profiles[dayMasterName] ?? profiles.Gui;
  const personalise = (value: string) => value.replaceAll("{name}", name);
  const strengthNote = strength === "Strong"
    ? `${name}'s preferred way of communicating may be easier to notice. Even so, it can change with the situation and the people involved.`
    : strength === "Weak"
      ? `${name}'s preferred way of communicating may emerge gradually, especially around people who feel safe and familiar.`
      : `${name}'s preferred way of communicating may change with the setting. Notice when these suggestions fit and when a different approach works better.`;
  return {
    introduction: `The Day Master offers a starting point for understanding how ${name} may receive information and respond during a conversation.`,
    strength_note: strengthNote,
    works_well: profile.works.map(personalise),
    avoid: profile.avoid.map(personalise),
    try_saying: profile.phrases.map(personalise),
    qualification: `Age, upbringing, relationships, and the rest of the Bazi chart also shape how ${name} communicates. Use these ideas as a starting point and keep what fits the person you know.`,
    basis: { factor: "Day Master communication style", value: dayMasterName },
  };
}
